import os

OBJ_DIR = os.path.join(os.getcwd(), '../obj/');
env = Environment(OBJPREFIX = OBJ_DIR)

common_libs = ['gtest', 'SDL', 'GL', 'pthread']
env.Append( LIBS = common_libs )

env.Program(target="test", source = ["test.cpp",
                                     "../src/GameStuff/map/GameMapGraph.cpp",
                                     "../src/GameStuff/FurnitureData.cpp",
                                     "../src/Xml.cpp",
                                     "../src/GameStuff/map/Room.cpp",
                                     "../src/GameStuff/Furniture.cpp",
                                     "../src/GameStuff/ItemContainer.cpp",
                                     "../src/TextureLoader.cpp",
                                     "../src/OSTools.cpp",
                                     "../src/ShaderProgram.cpp",
                                     "../src/Image.cpp",
                                     "../src/GameStuff/ItemDatabase.cpp",
                                     "../src/GameStuff/ItemInstance.cpp",
                                     "../src/gui/Text.cpp",
                                     "../src/Extensions.cpp",
                                     ])
